name: Pokedex Deployment Pipeline

on:
  push:
    branches:
      - Jimmy
  pull_request:
    branches: 
      - master
    types: [opened, synchronize]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - name: Install Dependencies
        run: npm install
      
      - name: Code Linting and Fix
        run: npm run eslint -- --fix
      
      - name: Build Project
        run: npm run build
      
      - name: Run Tests
